### PR TITLE
Fix celery app import

### PR DESCRIPTION
**Pull request by timthelion**
Maybe fixes https://github.com/auto-mat/django-import-export-celery/issues/15

### CODE REVIEW

**Comment by timthelion** [comment]
Can someone please test this and run black?

**Comment by timthelion** [comment]
And add some docs?

**Comment by platzhersh** [comment]
I added a new pullrequest with the requested changes: #18

**Comment by timthelion** [comment]
Hopefully this works ;) now released as 1.1.3
https://pypi.org/project/django-import-export-celery/

**Pull request closed without merging**
