### PR TITLE
fix TypeError: NoneType takes no arguments

### PR DESCRIPTION
**Pull request by Denkneb**
[issues #36](https://github.com/auto-mat/django-import-export-celery/issues/36)

### CODE REVIEW

**Comment by timthelion** [comment]
This is great if it works, but could you please explain why it works/what the problem is?

**Comment by Denkneb** [comment]
Hi,
this is due to the peculiarity of how transactions work in the database
this article explains it well
https://testdriven.io/blog/celery-database-transactions/

**Comment by timthelion** [comment]
OK, great, I get it now. would you mind running black so that travis is happy?

**Comment by Denkneb** [comment]
ok

**Comment by timthelion** [comment]
Ok great, thanks

**Comment by Denkneb** [comment]
Thanks

**Pull request merged**
