### PR TITLE
Add Basque language + optional function to exclude some DEFAULT_FORMATS

### PR DESCRIPTION
**Pull request by urtzai**
In this pull request are several changes:
- A new language translation was added: Basque (eu)
- A settings variable based function to remove some of tablib DEFAULT_FORMATS. This was done to simplify a user experience. This variable is a list of format strings written in lower case:
`
EXCLUDED_EXPORT_FORMATS = ["csv", "xls"]`
- Some files were black formated
- I've tried to make a email template translatable, but finally decided not to include

### CODE REVIEW

**Comment by urtzai** [comment]
@timthelion hi, is there anyone can review this PR?

**Comment by timthelion** [comment]
Oops, sorry, I thought one of the other maintainers would take care of it. The PR is mostly good but the new setting should be prefixed with `IMPORT_EXPORT_CELERY_` and documented in the README

**Review by timthelion — APPROVED** [review]

**Comment by timthelion** [comment]
Awesome! Thanks

**Comment by urtzai** [comment]
Thank for the merge! Do you mind to release at least a minor version package in pypi in order to install it in some Django instances?

**Pull request merged**
