### PR TITLE
Tweaks to the format fields + Make the processing_initiated field as readonly

### PR DESCRIPTION
**Pull request by rmaceissoft**
This PR includes:

- Use human readable format for the option text of format choices (to be consistent with django-import-export)
- Make format fields dynamic.
- Only include import/export formats that pass their respective tests (can_import/can_export).
- Make ImportJob's processing_initiated field as read-only (to be consistent with screenshoots at README)

### CODE REVIEW

**Comment by timthelion** [comment]
Looks good. Can you please run black so that travis will launch the tests?

**Comment by rmaceissoft** [comment]
hmm, black failed again but the check passing on my local after the last changes....
```
$ black --check ./import_export_celery
>> All done! ✨ 🍰 ✨
>> 16 files would be left unchanged.

cc: @timthelion 
```

**Comment by timthelion** [comment]
Ah yes, black, the code formatter so uncompromising it will not even make compromises with itself.

**Comment by rmaceissoft** [comment]
fortunately that will change soon with the [stable release](https://github.com/psf/black/projects/4) :-)

**Pull request merged**
