### PR TITLE
Fix for git describe during the automated pypi builds

### PR DESCRIPTION
**Pull request by marksweb**
This fixes the automated pypi builds.

### CODE REVIEW

**Comment by timthelion** [comment]
https://stackoverflow.com/a/58021463 This doesn't work. Not sure how to deal with it.

**Comment by marksweb** [comment]
@timthelion oh that's annoying. At the moment I'm not sure how to resolve.

In order to keep the automated release actions, moving to a hard coded version number fixes this. To make changing that easier bumpversion could be added also.

Or to keep using git describe, the pypi actions need removing and releases doing manually.

**Comment by timthelion** [comment]
OK, got it working with a date time based versioning scheme. https://test.pypi.org/project/django-import-export-celery/#history :)

**Comment by marksweb** [comment]
@timthelion Oh neat alternative. I'd still like to understand how the checkout action actually works and if it can do what was intended originally. Calling it "checkout" makes me thing git is involved and therefore using `describe` should be possible.

If nothing more than furthering my understanding I'd like to figure that stuff out. Might raise an issue on the checkout repo.

**Pull request merged**
